SG2044Pkg/AcpiPlatformDxe: Fix not found bug when call entry point
There are currently seven ACPI tables, corresponding to seven instances. When
reading the ACPI tables from the specified storage file one by one, we must
attempt to read eight times to exit the while loop. Therefore, we should not use
the last status to determine the return value. The following error has been fixed:

Loading driver at 0x0107F53E000 EntryPoint=0x0107F53F04A AcpiPlatform.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 107F5BF398
ProtectUefiImageCommon - 0x7F5BF040
  - 0x000000107F53E000 - 0x0000000000008000
SetUefiImageMemoryAttributes - 0x000000107F53E000 - 0x0000000000001000 (0x0000000000004000)
SetUefiImageMemoryAttributes - 0x000000107F53F000 - 0x0000000000005000 (0x0000000000020000)
SetUefiImageMemoryAttributes - 0x000000107F544000 - 0x0000000000002000 (0x0000000000004000)
PROGRESS CODE: V03040002 I0
Error: Image at 0107F53E000 start failed: Not Found

Signed-off-by: Jingyu Li <jingyu.li01@sophgo.com>